Poltio/poltio.github.io

ecom/home.html

- made a few changes to the ecom html

changed html

---

.prettierrc.json
ecom/home.html

- added prettier config
- removed unnecessary tailwind plugins
- moved poltio div to top

Prettier config

---

ecom/product.html
index.html

product html

---

ecom/home.html
index.html

- added dynamic widget example to ecom home page

add dynamic widget example

---

ecom/product_button.html

- Update product card section in prodcut button example

update product button example

---

ecom/home.html
ecom/product.html
sharafdg/SharafDGUAE.html
sharafdg/SharafDGUAEv2.html

- Update data-bg in all examples

update all examples data-bg

---

beko/Fridges_BEKO.html
ecom/home.html
ecom/product.html
ecom/product_button.html
sharafdg/SharafDGUAE.html
sharafdg/SharafDGUAEv2.html

Update params names

---

beko/Fridges_BEKO.html

- convert `beko.js` to `beko-test.js`

Update beko sdk 

---

beko/Fridges_BEKO.html
beko/Fridges_BEKO_AR.html

- add height param and update sdk version

Add height param to beko example

---

gtm/gtm.html
index.html

- Create gtm example page
https://poltio.github.io/gtm/gtm.html

create gtm implementation page

---

ecom/product_button.html

ecom/product_button.html?test
product page with hide button

product page hide button

---

ecom/product_flying.html
ecom/product_hide_button.html
index.html

flying example with and without buttons

flying with and without button

---

birdiejay/example.html

- Add birdiejay example
https://poltio.github.io/birdiejay/example.html

add birdiejay example

---

mediamarkt/example.html

- Add mediamarkt example (/mediamarkt/exaple.html)

Add mediamarkt example

---

index.html

closes Poltio/issues#5551
- Add live examples to index

create live examples section

---

ecom/product_active.html
ecom/product_expanded.html
index.html

ref Poltio/issues#5587
- Add initial position examples (active and expanded)

add initial position examples

---

gtm/gtm1.html
gtm/gtm2.html

- Added gtm1.html and gtm2.html

duplicate gtm page

---

birdiejay/example.html
ecom/home.html
ecom/product.html
ecom/product_active.html
ecom/product_bottom_left.html
ecom/product_button.html
ecom/product_center_left.html
ecom/product_center_right.html
ecom/product_expanded.html
ecom/product_flying.html
ecom/product_hide_button.html
ecom/product_top_left.html
ecom/product_top_right.html
gtm/gtm.html
gtm/gtm1.html
gtm/gtm2.html
hepsiburada/hepsiburada.html
index.html
mediamarkt/example.html

- Update tailwind images path
- Add gtm1 and gtm2 to index

update tailwind images path

---

arcelik_assistbox/a1.html
arcelik_assistbox/a2.html

- Create arcelik assisbox demo
poltio.github.io/arcelik_assistbox/a1.html
poltio.github.io/arcelik_assistbox/a2.html

create arcelik assistbox demo

---

newcards/embed.html
newcards/embed_single_result.html
newcards/embed_w_leads.html

- Add new result cards embed examples 
- Multiple result example
- Single result example
- Result with leads example
http://poltio.github.io/newcards/embed.html
http://poltio.github.io/newcards/embed_single_result.html
http://poltio.github.io/newcards/embed_w_leads.html

Add new result cards embed example

---

newcards/beko.html
newcards/diverge.html
newcards/embed_single_result.html
newcards/mavi.html
newcards/mavi_w_price.html
newcards/reis.html
newcards/results.html
newcards/results_w_leads.html
newcards/teknosa.html
newcards/yves.html

Reverts Poltio/poltio.github.io#121

Revert "update result cards widget url to prod"

---

new_home/index.html
new_plp/plpv1.html

- **update plp banner trigger style**
- **bento grid integration**
- **add nav to pages**

Add bentogrid to list page

---

baume/www.baume-et-mercier.com/en/home.html

- update disclaimer param in baume demo

update disclaimer param in baume demo

---

fullURL/poltioFullUrl.html

```https://poltio.github.io/fullURL/poltioFullUrl.html```

add get url from script example

---

ecomtrack/checkout.html
ecomtrack/success.html

https://poltio.github.io/ecomtrack/success.html

add conversion tracking script for test

---

test-cases/sdk-cta-open.html
test-cases/sdk-div.html
test-cases/sdk-iframe.html
test-cases/sdk-manuel-trigger.html
test-cases/sdk-xp.html
test-cases/snippet-div.html

- Add sdk test cases
- https://poltio.github.io/test-cases/sdk-div.html
- https://poltio.github.io/test-cases/sdk-iframe.html
- https://poltio.github.io/test-cases/sdk-xp.html
- https://poltio.github.io/test-cases/sdk-cta-open.html
- https://poltio.github.io/test-cases/sdk-manuel-trigger.html
- https://poltio.github.io/test-cases/snippet-div.html

add sdk test cases

---

test-cases/double-sdk-load.html
test-cases/index.html
test-cases/snippet-cta-open.html
test-cases/snippet-iframe.html
test-cases/snippet-manuel-trigger.html
test-cases/snippet-xp.html

- Add more test cases
- Add test cases index

Add more test cases and add index 
